FROM golang:1.26-bookworm

# Instal Air untuk Hot-Reload (seperti Nodemon)
RUN go install github.com/air-verse/air@latest

# Instal Dependensi Sistem (LibreOffice & FFmpeg)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice-core \
    libreoffice-writer \
    libreoffice-calc \
    libreoffice-impress \
    fonts-liberation \
    ca-certificates \
    ffmpeg \
    python3 \
    python3-mutagen \
    curl \
    nodejs \
    && rm -rf /var/lib/apt/lists/*

# Install versi terbaru yt-dlp langsung dari GitHub (apt package biasanya kadaluarsa)
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp \
    && chmod a+rx /usr/local/bin/yt-dlp

WORKDIR /app

# Ketika container menyala, jalankan Air
CMD ["air"]
