version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: henka_backend_dev
    ports:
      - "8080:8080"
    volumes:
      # Melakukan sinkronisasi folder lokal Mac Anda dengan folder /app di dalam Docker
      - .:/app
    environment:
      # Pindahkan cache Go agar tidak konflik dengan cache sistem Mac Anda
      - GOCACHE=/app/.gocache
